# Generated by Django 3.0.7 on 2020-06-04 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_post_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
    ]
