# Generated by Django 3.0.7 on 2020-06-04 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_group_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
    ]
